# config.yaml — пример конфигурации для DNS-прокси

# 1) Upstream-сервер, к которому идут «разрешённые» запросы
upstream:
  host: "8.8.8.8"    # IP-адрес upstream-DNS
  port: 53           # порт upstream

# 2) Чёрный список (перечень блокируемых имён)
# Поддерживаются wildcard (*) для блокировки групп доменов:
# - example.com - блокировка только этого домена
# - *.example.com - блокировка всех поддоменов (но не сам домен)
# - *.test.* - блокировка всех доменов содержащих ".test."
blacklist:
  - "example.com"
  - "*.badwebsite.org"  # блокирует все поддомены badwebsite.org
  - "malware.test"
  - "tracker.*"         # блокирует все домены начинающиеся с tracker.

# 3) Тип ответа для заблокированных доменов:
#    - NXDOMAIN  → «имя не существует» (RCODE=3)
#    - REFUSED   → «отказано»          (RCODE=5)
#    - REDIRECT  → возвращаем A-запись на указанный IP
blacklist_response_type: "REFUSED"

# 4) IP для перенаправления (только если response_type = REDIRECT)
redirect_ip: "127.0.0.1"

# 5) Таймаут чтения параметров из конфигурации (текущий)
reload_interval: 60   # секунд
